version: '3'

services:
  json-to-swagger-api:
    image: golang:1.21.0
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/go/src/app
    working_dir: /go/src/app
    command: go run main.go
    networks:
      - json-to-swagger-network
  json-to-swagger-ui:
    image: node:16
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    command: ["npm", "run", "start"]
    networks:
      - json-to-swagger-network
networks:
  json-to-swagger-network:
    driver: bridge




    
